### ISSUE TITLE
Enable Dependency Injection 

### ISSUE THREAD

**Issue by TsuyoshiUshio** [kazumihirose/Covid19Radar#28]
Azure Functions ですが、HttpClientや、CosmosDBのクライアントは基本的にシングルトンで保持する必要があるため、DIを使う形式にリファクタリングするのが良いと思います。

Acceptance Criteria: 
* [ ] DIにより、CosmosDBのクライアントがFunctionsにInjectionされている。
* [ ] AzureFunctionsのクライアントがstatic から non-static クラスに変更されている。

**Comment by darkcrash** [comment]
取り急ぎDI化してみました
