### ISSUE TITLE
Send to Azure API (Fucntions ?) via Cosmos's GraphDB

### ISSUE THREAD

**Issue by kazumihirose** [kazumihirose/Covid19Radar#5]

**Comment by kazumihirose** [comment]
Function
今のところ、REST APIの仕様は決まってない。
必要なのは二つのAPI
既にモデルはあって、Covid19Radar/Covid19Radar/Covid19Radar/Model/UserData.cs

 


User
GET/POST
{
    UUID:"String",
    UserID:"String",
    Major:"String",
    Minor:"String"
}

 

UUIDは同じものが来ます。BLEの仕様上同じUUID同士のビーコンを検出します。
Majorは0-65536のいずれか、Minorも同じ、これは初回登録時にこのUserAPIから払い出し（一意で）、
UserIDは、これらの結果からString.Format("{0}.{1}.{2}", Uuid, Major.PadLeft(5, '0'), Minor.PadLeft(5, '0'));
桁数分の0パディングしたもの。
Githubに既にFuncのプロジェクトがある、結果はSQLDBでもCosmosDBでもどこでもOK。
可視化はPower BIのNetwork visualizer検討中

**Comment by darkcrash** [comment]
何もしないと何も進まないということで
/api/Beacon
/api/User

の2つでとりあえず、API Definition ブランチを上げてみました。
