### ISSUE TITLE
Develop Generate UserID (Major, Minor) API

### ISSUE THREAD

**Issue by TsuyoshiUshio** [kazumihirose/Covid19Radar#50]
サーバー側で、ユニークな Major, Minor の値を生成して、クライアントに返却します。ロジックは、`Major:0, Minor:0` から初めて `Major:0, Minor: 65536` に到達したら `Major:1, Minor: 0` が次の値になります。クライアントに返却されるモデルは `UserDataModel`です。モデルの詳細は、`doc/domain-model.md` をご確認ください。

## デザイン

上記の通り

## 依存
なし

## 完了条件
* [ ] データモデルがディスカッションされて、本Issueでシェアされている
* [ ] 上記の仕様が実装されている
* [ ] Unit Test が記述されており、CIでパスしている
* [ ] Pull Request でレビューが実施されている
* [ ] GitHub Action で開発環境にデプロイされており、動作確認が行われている

**Comment by IshikoroKoishi** [comment]
使用に関して質問です
このUserID Generatorは、すでに払い出し済みのIDをどのように把握するのでしょうか
サーバ側の再起動等でも一貫性を維持するためにはなんらかの方法で永続化すると思うのですが、
すでに決まっていたりしますか？

**Comment by TsuyoshiUshio** [comment]
現在のところ、CosmosDBは使う方向で決まっていますが、他のデータベースシステムも併用する可能性もあります。払い出しの場合はCosmosDBで実装でいい気がします。その払い出し済みのIDをどう管理するか、どんなデータ構造で格納するかは決まっていないので、discodeapp かここでディスカッションするといいと思います。（すみません、完了条件に含めるべきでしたね）

**Comment by IshikoroKoishi** [comment]
discordで上がっていた案は、ドキュメントDBに下みたいなデータが格納されるようなイメージであってますか?
```json
{
    "id": "1",
    "major": "<最後に払い出したMajor値>",
    "minor": "<最後に払い出したMinor値>"
}
```

**Comment by TsuyoshiUshio** [comment]
はい。そういうイメージだと思います！

**Comment by IshikoroKoishi** [comment]
これやってみようと思いますので、アサイン頂けないでしょうか。

**Comment by IshikoroKoishi** [comment]
クライアント側から見た動作としては、
1. api/UserにGETメソッド呼び出し
2. 新規Major, Minor値が設定されたUserDataが返る
でいいですかね?

**Comment by TsuyoshiUshio** [comment]
@IshikoroKoishi  すみません、今開発のメインが、Slackの方にいっていいて、そちでKanbanがつくられているので、そっちでアサインしてもらえるようにしましょう！Slack見れます？みしみれてなかったら、discordapp の方で連絡してみてください。
