### ISSUE TITLE
Cancel Positive API

### ISSUE THREAD

**Issue by TsuyoshiUshio** [kazumihirose/Covid19Radar#53]
陽性になっている人が陰性化した場合に、陽性者の解除を実施します。それによって、一度陽性判定された人が、陽性者として判定されることを防ぎます。

このストーリは、「陽性者の解除」のみであり、解除は別ストーリとなります。

## デザイン

[Create Positive API](https://github.com/kazumihirose/Covid19Radar/issues/52)で作成したデータの削除もしくは、論理削除を行います。

## 依存
https://github.com/kazumihirose/Covid19Radar/issues/52

## 完了の定義
* [ ] 削除の仕様に関して議論されて、このIssueに決定事項が記述されている
* [ ] 削除の実装ができている
* [ ] UnitTestが記述されている、CIでパスしている
* [ ] GitHub Action により開発環境にデプロイされており、動作確認がされている

**Comment by changeworld** [comment]
＞作成したデータの削除もしくは、論理削除を行います。

以下の観点から別案を提案します。

* 論理削除はアンチパターンになりうる
* 「陽性→陰性（回復）→陽性（再疾患）」といったケースを考慮すると、ステータスという考え方の方が適している可能性が高い

そのため、削除や論理削除ではなく

* 「陰性（データとしてそもそも登録しない）」
* 「陽性（ステータス１）」
* 「回復（ステータス２）」
* 「抗体あり（ステータス３）」

といったステータスにするのはいかがでしょうか。

**Comment by TsuyoshiUshio** [comment]
ご提案ありがとうございます。ステータスが状態遷移するのはよさげですね。https://github.com/kazumihirose/Covid19Radar/issues/52 のストーリにも関係がありそうです。

**Comment by kazumihirose** [comment]
こちら、ご意見を参考に取り入れました。ありがとうございます。
