### ISSUE TITLE
Create batch for creating table for PowerBI Netwrok Navigator

### ISSUE THREAD

**Issue by TsuyoshiUshio** [kazumihirose/Covid19Radar#54]
[濃厚接触API](https://github.com/kazumihirose/Covid19Radar/issues/48)で、データがCosmosDBに登録されたのをトリガーに、ChangeFeedにより、[
NetworkNavigator](https://github.com/microsoft/PowerBI-visuals-NetworkNavigator)向けのデータを 作成します。他のデータと業務知識に関しては`doc/domain-model.md`をご覧ください

## デザイン

下記の調査が終了しだい、詳細をブレークダウンしてください。データが生成されるデータベースもComosDBではなく、SQLデータベースである可能性もあります。

## 依存
下記のIssueで、現在調査中です。この調査が終了しだい、本ストーリが実行可能です。
https://github.com/kazumihirose/Covid19Radar/issues/14
https://github.com/kazumihirose/Covid19Radar/issues/48

## 完了条件
* [ ] 上記の調査の完了を持って、どのようなデータを生成するかが議論され、本Issueに記述されている
* [ ] 具体的なストーリをIssueとして作成されているもしくは、本Issueを編集して、具体的な完了条件に落とし込まれている。

**Comment by kazumihirose** [comment]
コア、データサイドチームで対応準備中
