### ISSUE TITLE
Switch to use regular BLE service instead of iBeacon

### ISSUE THREAD

**Issue by mash** [kazumihirose/Covid19Radar#59]
https://github.com/kazumihirose/Covid19Radar/blob/master/doc/domain-model.md
を拝見すると、スマートフォンアプリはiBeaconのふりをする仕様です。

iOSでは、iBeaconのふりをすることはBackgroundではできません。(Androidについてはわかりません、識者の方お願いします)

> Apps that use their underlying iOS device as an iBeacon must run in the foreground.

https://developer.apple.com/documentation/corelocation/turning_an_ios_device_into_an_ibeacon_device
Also https://stackoverflow.com/a/41040326/105194

*アプリを常時立ち上げて移動することは考えにくい* ですから、Backgroundでも濃厚接触を検出することができる方がよいでしょう。

iOSでは bluetooth-peripheral Background Execution Modeを指定することで、Backgroundでも、BLEのPeripheralとしてAdvertisingできます。

> In addition to allowing your app to be woken up to handle read, write, and subscription requests from connected centrals, the Core Bluetooth framework allows your app to advertise while in the background state.

https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html

同様に bluetooth-central Background Execution Modeを指定することで、BackgroundでもCentralとしてPeripheralをDiscoverできます。

BackgroundのAdvertisingではBLEのGatt service UUIDがApple独自仕様のspecial “overflow” areaに入るため、"BackgroundでadvertisingしているiOSアプリはiOSアプリからのみDiscoverできる(つまりAndroidからはできない)"という条件付きですが。

---

ということで、iBeaconではなく、
Read Characteristicを1つ、Write Characteristicを1つ
含むGATT Serviceに変更することを提案します。

これにより、現状ではiOSデバイス間では接触の検出ができなかった問題を解決できます。

Read/Writeでやり取りデータは、domain-model.mdにある `MajorとMinorのセットがユーザの識別子` に当たるような情報を考えています。
Major, Minorのみの識別子空間であれば32bitに限定されていましたが、
iBeaconから離れることで識別子は64bit化できます。

---
ここからは本issueの範囲外ですが、
64bit化できれば、ユーザの識別子は、プライバシーを考慮し1日以下の間隔で新しい値に更新することも可能です。

現在のアーキテクチャではサーバ側が重い、、という認識が生まれてきているのではないでしょうか？ :)

Decentralizedな考え方も含めたアーキテクチャ設計についてはここに書きました。
https://gist.github.com/mash/281e8e5ee7188a659213c7ecc363e3b2

**Comment by TsuyoshiUshio** [comment]
貴重なご提案ありがとうございます。discodeappの方でシェアしてみます。
一番最後のアーキテクチャ設計の部分なのですが、UserIDを一定期間で、変更していく設計になっています。そして、サーバー側から陽性者のIDが端末で取得できるようになっています。この場合、陽性者のIDも更新されていくので、陽性者のヒストリ含めて取得することになることになりそうですが、このイメージは合っていますか？ちなみに陽性者のリストのAPIは、私もサーバー側での判定が面倒そうだなと感じていたので可能性はとても感じています！

**Comment by mash** [comment]
> そして、サーバー側から陽性者のIDが端末で取得できるようになっています。この場合、陽性者のIDも更新されていくので、陽性者のヒストリ含めて取得することになることになりそうですが、このイメージは合っていますか？

自分が書いたときには、陽性者のIDのリストでなく、接触者のIDのリスト(=陽性者がBLEで検出した人のIDのリスト)と書いたつもりでしたが、
陽性者のIDのリストでもよいかもしれません。その方が接触者よりも人数が少ないと考えられるので、データ量が少ないですね。

> この場合、陽性者のIDも更新されていくので、陽性者のヒストリ含めて取得することになることになりそうですが、このイメージは合っていますか？

はい。

**Comment by TsuyoshiUshio** [comment]
なるほど。勘違いしていましたが、理解しました！discordapp の方でシェアしておきましたので、しばしお待ちください（私はUSに在住なので、みなさんとタイムゾーンが違うので、みんな寝てると思います）もしよかったら、mashさんもdiscordapp（チャット）に招待しますがいかがですか？

**Comment by mash** [comment]
github.com/mash と discordにいるmashは同一人物ですので入れていますよ 👍

**Comment by TsuyoshiUshio** [comment]
了解ですｗｗｗ

**Comment by changeworld** [comment]
対応表
https://onedrive.live.com/redir?resid=AFEA52B867B4A879!13259&authkey=!AIwVObPi4S85w84&ithint=file%2cxlsx&e=w1XXUV
