### ISSUE TITLE
A blank page is displayed when the app is launched for the second time

### ISSUE THREAD

**Issue by takapi-Jr** [kazumihirose/Covid19Radar#71]
デバイスのアクセス許可画面で操作以降、タスクキルすると次回以降のアプリ起動で白紙ページが表示されます。
位置情報のアクセスを許可する/許可しないに関わらず上記現象が発生します。

**Overview**
After the operation on the device access permission screen, if you kill the task, a blank page will be displayed at the next application start.
The above phenomenon occurs regardless of whether access to location information is permitted or not.
**Test terminal**
Zenfone 2(Android 6.0.1)
Zenfone 4(Android 8.0.0)
**Build Number**
100

**Comment by takuya1981** [comment]
It's reproduced in my environment.
- Blackview A60 Pro(Android 9)
- GALAXY S5 ACTIVE SC-02G docomo(Android 6.0.1)
Build number : 100

Furthermore, start page is shown after rotating to landscape from portrait.

**Comment by taka1985** [comment]
同じでした。
確かに、表示方向をかえる設定をして変えたところ、表示されました。

It's reproduced in my environment.

Sharp SH-01K docomo(Android 8.0.0 build 02.00.05)
App Build number : 100
Furthermore, start page is shown after rotating to landscape from portrait.

**Comment by huideyeren** [comment]
私も同じです。

It's reproduced in my environment too.

Fujitsu F-04K docomo(Android 9 Build V48R047A)
App Build number : 101
Furthermore, start page is shown after rotating to landscape from portrait.

**Comment by takapi-Jr** [comment]
解消しました。

It has been resolved.
Build number : (Android)104
