### ISSUE TITLE
Phone number can only be entered in 10 digits.

### ISSUE THREAD

**Issue by huideyeren** [kazumihirose/Covid19Radar#74]
On the status setting screen, I can enter only 10 digits for the phone number.
Since the Japanese mobile phone number is 11 digits, the last 1 digit cannot be entered.

（以下日本語）
ステータス設定画面で、電話番号が10桁までしか入力できません。
日本の携帯電話番号は11桁なので、最後の1桁が入りません。

![Screenshot_20200418-124910](https://user-images.githubusercontent.com/1094632/79627791-4f9c7880-8176-11ea-9cff-7dcb7dbccdb6.png)

Fujitsu F-04K docomo(Android 9 Build V48R047A)
App Build number : 101

**Comment by huideyeren** [comment]
I can only enter up to 10 digits for the phone number on the iPhone 7 Plus.

**Comment by rupic-jp** [comment]
I was able to confirm the same phenomenon on the iPhone 8.

**Comment by A-MiniKuma** [comment]
同じ現象がAndroid 8.0  Xperiaでも起きました。

**Comment by yokawasa** [comment]
I had the same issue - IPhoneXS
![86C351C9-6331-46F8-A0B4-E2DCC90F034F](https://user-images.githubusercontent.com/82332/79928684-8b895380-847e-11ea-8087-e08275826079.jpeg)
