### ISSUE TITLE
Home screen is not displayed.

### ISSUE THREAD

**Issue by takapi-Jr** [kazumihirose/Covid19Radar#94]
登録完了画面からホーム画面に遷移できない。
アプリを開き直すと「Exception has been thrown by the target of an invocation.」のみ表示された画面になる。

**Overview**
You cannot transition from the registration completion screen to the home screen.
When you reopen the app, the screen will show only "Exception has been thrown by the target of an invocation."
**Test terminal**
Zenfone 2(Android 6.0.1)
Zenfone 4(Android 8.0.0)
**Build number**
181

![Screenshot_20200422-211005](https://user-images.githubusercontent.com/25080529/79980597-4bf25400-84de-11ea-96e2-b598837e605f.jpg)

**Comment by testedquality** [comment]
登録完了画面からホーム画面に遷移できない。アプリを開き直すと「Exception has been thrown by the target of an invocation.」のみ表示された画面になる。
**Test terminal**
HUAWEI P10 lite (Android 8.0.0)
**Build number**
Version: 1.0.0.234-1 - dev

**Comment by takapi-Jr** [comment]
解消しました。

It has been resolved.
Build number : (Android)185
